apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: activemq-operators
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: activemq-operators
      namespace: activemq-operators
    spec: {}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: amq-broker-rhel8
      namespace: activemq-operators
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: amq-broker-rhel8
      source: redhat-operators
      sourceNamespace: openshift-marketplace
