apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: kiali-operators
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: kiali-operators
      namespace: kiali-operators
    spec: {}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: kiali-operator
      namespace: kiali-operators
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: kiali-ossm
      source: redhat-operators
      sourceNamespace: openshift-marketplace
