apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: sso
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: sso
      namespace: sso
    spec: {}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: rhsso-operator
      namespace: sso
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: rhsso-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
